NEW: Added discourse verify
ceramicstudio/identitylink-services pull request #16
Opened 2021-02-23 01:29 UTC by venarius

Hey,

this PR adds discourse as a verification source. Had a lot of fun adding this which is why I forgot to even apply for work on Gitcoin haha. I applied for work now 😅 

Any feedback is appreciated!

cc @oed

2021-02-23 08:57 UTC, oed commented
Cool @venarius!

So this implementes the api in #10? I assume you are just fetching the thread over the normal doamin and not using an auth token (as described here: https://github.com/ceramicstudio/identitylink-services/issues/10#issuecomment-783843529). Had a quick look over the code and looks ok. Will have to do a more thorough review later this week!

Will at least approve you to start working on it on gitcoin 😅

2021-02-23 11:07 UTC, venarius commented
> So this implementes the api in #10? I assume you are just fetching the thread over the normal doamin and not using an auth token (as described here: [#10 (comment)](https://github.com/ceramicstudio/identitylink-services/issues/10#issuecomment-783843529)).

Yes, exactly 😊 You can fetch a public thread over API without needing an auth token.

2021-02-25 12:40 UTC, oed reviewed
Code looks good. How can I test this most easily against a real discourse forum?

Tests pass locally.

2021-02-25 13:16 UTC, venarius commented
> Code looks good. How can I test this most easily against a real discourse forum?

You can e.g. use a public thread link of the meta discourse forum: https://meta.discourse.org/t/bootsnap-permissionerror/181002

And then select a random post there und use their username and a random text from their post as did

And then test using that username, did and link 😀

2021-02-25 15:56 UTC, oed requested changes
Can you add the api descriptions from https://github.com/ceramicstudio/identitylink-services/issues/10#issuecomment-781263712 in the `API.md` file?

2021-03-01 16:10 UTC, venarius commented
@oed fyi, in case you didn't see that I added the flows to the markdown file 😅

2021-03-01 16:26 UTC, oed commented
No I did, thanks. Will get around to reviewing this shortly, sorry for the slow turnaround here.

2021-03-01 22:06 UTC, topocount commented on API.md
> +
nit: what exactly is a "thread" in the context of discourse? It might be good to be precise when distinguishing between a "topic" and a "post" in discourse. Topics are equal to threads in this case, I believe, but a specific post is what will probably contain the DID, right?

This is just my opinion, but it might be helpful if the same language is used as it exists in the discourse docs and API.

2021-03-01 23:42 UTC, venarius commented on API.md
> +
Yes, topics are called threads in discourse :) I will make that more clear. Thanks for the input!

2021-03-02 13:08 UTC, oed commented
Looks like you missed adding the functions to `serverless.yml`.

2021-03-02 13:12 UTC, oed requested changes
Looks like you forgot to add the functions to `serverless.yml`.

Also would you mind rebasing on latest master?

2021-03-03 17:40 UTC, venarius commented
I also added updated the discourse manager to now work with the new AWS Cloudfront redis layer

2021-03-08 10:36 UTC, oed commented
@venarius I'm running into an issue when I try to test the entire flow. Are you sure you tested the entire flow with both requests? 

The error I'm seeing:
```sh
$ curl -X POST http://localhost:3000/api/v0/request-discourse -d '{ "did": "did:key:z6MktapC8fCR3TE9G9JP2WCGi3tsKe888Jea6YqqkQSSRa7r", "threadUrl": "https://forum.metagame.wtf/t/who-are-you-really/142", "username": "oed" }'

{"status":"success","data":{"challengeCode":"9lZSUiSbXdBvmII3wPEsJJCZXZbseBS4"}}


 $ curl -X POST http://localhost:3000/api/v0/confirm-discourse -d '{ "jws": "eyJhbGciOiJFZERTQSIsImtpZCI6ImRpZDprZXk6ejZNa3RhcEM4ZkNSM1RFOUc5SlAyV0NHaTN0c0tlODg4SmVhNllxcWtRU1NSYTdyI3o2TWt0YXBDOGZDUjNURTlHOUpQMldDR2kzdHNLZTg4OEplYTZZcXFrUVNTUmE3ciJ9.eyJjaGFsbGVuZ2VDb2RlIjoiOWxaU1VpU2JYZEJ2bUlJM3dQRXNKSkNaWFpic2VCUzQifQ.R1jC07yu4o-56tKbQtqQ-ersdh38exUCTRRjq8mqDzKVhl3g3Ouirn1ksngJ0WGqxfhFHEI1r9N2YOpejCbsBQ" }'

{"status":"error","message":"error while trying verify discord. TypeError: this.discordMgr.confirmRequest is not a function"}
```

For reference, the script I'm using to generate the DID and sign the challenge: 

```js
const fn = async () => {
  const prompt = require('prompt')
  const { randomBytes } = require('@stablelib/random')
  const { Ed25519Provider } = require('key-did-provider-ed25519')
  const { DID } = require('dids')
  const resolver = {
    ...require('@ceramicnetwork/key-did-resolver').default.getResolver(),
    ...require('web-did-resolver').getResolver()
  }
  const Resolver = require('did-resolver')
  const provider = new Ed25519Provider(randomBytes(32))
  const did = new DID({ provider, resolver })
  const { verifyJWT } = require('did-jwt')

  await did.authenticate()
  console.log('DID:', did.id)

  prompt.start()
  prompt.get(['challengeCode'], async (err, { challengeCode }) => {
    const jws = await did.createJWS({ challengeCode })
    console.log('JWS:', jws.signatures[0].protected + '.' + jws.payload + '.' + jws.signatures[0].signature)

    prompt.get(['vc'], async (err, { vc }) => {
      const res = await verifyJWT(vc, { resolver: new Resolver.Resolver(resolver) })
      console.log('response', res)
    })

  })
}
fn()
```

2021-03-08 10:51 UTC, venarius commented
> @venarius I'm running into an issue when I try to test the entire flow. Are you sure you tested the entire flow with both requests?

I have fixed the import. I could not really test the whole flow besides running the tests because the Readme is missing instructions on how to run the server. The only thing it states there is to run ```sls offline --host 0.0.0.0``` but I don't know what the "sls" program is.

Sorry for that 😅

2021-03-08 11:32 UTC, oed commented
sls should be equivalent to running `serverless offline`

It seem like it's working now, however there is one main problem. It only works if I refer to my specific post:

This works:
`https://forum.metagame.wtf/t/who-are-you-really/142/104`

This doesn't:
`https://forum.metagame.wtf/t/who-are-you-really/142`

It would be nice if I didn't have to link to the specific post that the user made, just reference the thread and find the users post.

2021-03-08 13:04 UTC, venarius commented
Yep, that seems true. Discourse seems to chunk a thread with a lot of posts. I didn't check for that. I added a param which will tell discourse to print all chunks.

Can you test again?

2021-03-08 13:28 UTC, oed approved these changes
Ok, aweseome it's working now!

2021-03-08 17:23 UTC, merged